# Generated by Django 3.2 on 2022-07-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=20, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('data_created', models.DateTimeField(default='2022-07-09', verbose_name='Время создания')),
                ('due_date', models.DateField(default='2022-07-09', verbose_name='Время дедлайна')),
                ('author', models.ForeignKey(default='нет автора', on_delete=django.db.models.deletion.CASCADE, to='todo_app.author')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тэга')),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания тэга')),
                ('is_active', models.BooleanField(default=True)),
                ('records', models.ManyToManyField(to='todo_app.Record')),
            ],
            options={
                'verbose_name': 'Тег записи',
                'verbose_name_plural': 'Теги записи',
            },
        ),
    ]
