# Generated by Django 3.2 on 2022-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='records',
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(to='todo_app.Tag'),
        ),
        migrations.AlterField(
            model_name='record',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='due_date',
            field=models.DateField(auto_now_add=True, verbose_name='Время дедлайна'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Тэг используется'),
        ),
    ]
